### ISSUE TITLE
Panic on Symbolic Links with Permissions

### ISSUE THREAD

**Issue by mmstick** [ogham/exa#123]
Expected:

```
/bin/ls: cannot read symbolic link cwd: Permission denied
/bin/ls: cannot read symbolic link root: Permission denied
/bin/ls: cannot read symbolic link exe: Permission denied
total 0
-r-------- 1 root root 0 Sep  9 17:56 auxv
-r--r--r-- 1 root root 0 Sep  9 17:56 cgroup
--w------- 1 root root 0 Sep  9 17:56 clear_refs
-r--r--r-- 1 root root 0 Sep  9 17:56 cmdline
-rw-r--r-- 1 root root 0 Sep  9 17:56 comm
-rw-r--r-- 1 root root 0 Sep  9 17:56 coredump_filter
.........
```

What actually happens: (src/fs/file.rs:168)

```
thread 'main' panicked at 'This was not a link!', src/fs/file.rs:168
stack backtrace:
   1:     0x55d05a6461a3 - std::sys::backtrace::tracing::imp::write::h46f28e67d38b4637
   2:     0x55d05a64aabd - std::panicking::default_hook::{{closure}}::h1d3243f546573ff4
   3:     0x55d05a649d4a - std::panicking::default_hook::h96c288d728df3ebf
   4:     0x55d05a64a348 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   5:     0x55d05a50fe43 - std::panicking::begin_panic::h0914615a412ba184
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:383
   6:     0x55d05a5332ab - exa::fs::file::File::link_target::hfba9251dc71694ae
                        at /home/mmstick/Documents/exa/src/fs/file.rs:168
   7:     0x55d05a543977 - exa::output::filename::h3e4cc461dd053aa4
                        at /home/mmstick/Documents/exa/src/output/mod.rs:44
   8:     0x55d05a4b552f - exa::output::details::Details::add_files_to_table::h768858175871bfe8
                        at /home/mmstick/Documents/exa/src/output/details.rs:315
   9:     0x55d05a4b7239 - exa::output::details::Details::view::h99d42af71cb179dd
                        at /home/mmstick/Documents/exa/src/output/details.rs:219
  10:     0x55d05a4c0fce - <exa::Exa<'w, W>>::print_files::he7cedc01cd78ce05
                        at /home/mmstick/Documents/exa/src/exa.rs:166
  11:     0x55d05a4bfe4f - <exa::Exa<'w, W>>::print_dirs::hcdb846b1720038c4
                        at /home/mmstick/Documents/exa/src/exa.rs:154
  12:     0x55d05a4c1efc - <exa::Exa<'w, W>>::run::h10801069074c31c6
                        at /home/mmstick/Documents/exa/src/exa.rs:102
  13:     0x55d05a4ff8bf - exa::main::he05879b008ea21c0
                        at /home/mmstick/Documents/exa/src/bin/main.rs:13
  14:     0x55d05a652586 - __rust_maybe_catch_panic
  15:     0x55d05a6495c1 - std::rt::lang_start::haaae1186de9de8cb
  16:     0x55d05a502c93 - main
  17:     0x7f2e2840d61f - __libc_start_main
  18:     0x55d05a49d098 - _start
  19:                0x0 - <unknown>
```

**Comment by ogham** [comment]
Panics bad. Will fix.

**Comment by ogham** [comment]
Sorry, I’m having trouble reproducing this. Could you provide what commands you were running, and what `ls` outputs for the same command? (I appreciate that it’s been a while)

**Comment by mmstick** [comment]
Go to a process directory in `/proc/$PID` and simply run `exa`
