### ISSUE TITLE
exa thread panicked

### ISSUE THREAD

**Issue by alem0lars** [ogham/exa#428]
When doing exa in large directory tree, exa gives the following error:

![screenshot-2018-22-18 10 22 57 665](https://user-images.githubusercontent.com/336957/47141022-012bc680-d2c0-11e8-8d61-c027ce1e27a3.png)

With backtrace enabled:

![screenshot-2018-23-18 10 23 29 689](https://user-images.githubusercontent.com/336957/47141021-012bc680-d2c0-11e8-98d3-0bc4fdd0f2ce.png)

**Comment by ogham** [comment]
What a useless stacktrace! (It’s what I get for stripping the binary)

Could you tell me how long exa runs for before crashing?

**Comment by musq** [comment]
exa version v0.9.0 (compiled from 479fdea)

It works with only `exa`.

But crashes immediately with `exa --long`.

```
$ RUST_BACKTRACE=full exa --long
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(6795364578.871345152s)', src/libcore/result.rs:999:5
stack backtrace:
   0:     0x5598167a0623 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h6485381528590a55
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x55981679eb3b - std::panicking::default_hook::{{closure}}::he20974adbefcc046
                               at src/libstd/sys_common/backtrace.rs:71
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   2:     0x55981679db60 - std::panicking::rust_panic_with_hook::h057ff03eb4c8000f
                               at src/libstd/panicking.rs:211
                               at src/libstd/panicking.rs:474
   3:     0x55981679d74d - std::panicking::continue_panic_fmt::ha6d6ae144369025b
                               at src/libstd/panicking.rs:381
   4:     0x5598167aad85 - rust_begin_unwind
                               at src/libstd/panicking.rs:308
   5:     0x5598167aea1b - core::panicking::panic_fmt::hc4f83bfed80aeabd
                               at src/libcore/panicking.rs:85
   6:     0x559816778b7f - core::result::unwrap_failed::h3f02982f072a685f
   7:     0x55981675a880 - exa::output::table::Table::display::hb46c2f67080359d1
   8:     0x559816761ae1 - <F as scoped_threadpool::FnBox>::call_box::hd8c528f0ed6a1d05
   9:     0x55981678b51c - std::sys_common::backtrace::__rust_begin_short_backtrace::h4e6acfefbed69525
  10:     0x55981678bccb - core::ops::function::FnOnce::call_once{{vtable.shim}}::h50fee7b35766913e
  11:     0x5598167aa8ed - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h805c3cc89d534c05
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  12:     0x5598167ab7d7 - std::sys::unix::thread::Thread::new::thread_start::h6f10b78f26c98dc6
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
                               at src/libstd/sys_common/thread.rs:13
                               at src/libstd/sys/unix/thread.rs:79
  13:     0x7f258d9f36b9 - start_thread
  14:     0x7f258d51341c - clone
  15:                0x0 - <unknown>
Aborted (core dumped)
```

**Comment by ogham** [comment]
I concur that this is #670, which has had its fix merged and will go out with the next release.
