### ISSUE TITLE
Panic on exa -lh --git --all

### ISSUE THREAD

**Issue by aral** [ogham/exa#779]
## Version

exa v0.9.0

## Command

```
exa -lh --git --all
```

## System details

```
OS: elementary OS 5.1.7 Hera x86_64 
Host: LabTop Mk IV 
Kernel: 5.4.0-58-generic 
Uptime: 2 days, 6 hours, 1 min 
Packages: 2047 
Shell: zsh 5.4.2 
Resolution: 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel i7-10710U (12) @ 4.700GHz 
GPU: Intel Device 9bca 
Memory: 6819MiB / 15883MiB
```

## Stack trace

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SystemTimeError(2147483648s)', /home/aral/.cargo/registry/src/github.com-1ecc6299db9ec823/exa-0.9.0/src/fs/file.rs:331:70
stack backtrace:
   0:     0x564e1fe70a6a - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x564e1fe70a6a - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x564e1fe70a6a - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x564e1fe70a6a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x564e1fdfbc2c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x564e1fe700c1 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x564e1fe6fb2a - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x564e1fe6fb2a - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x564e1fe6fb2a - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x564e1fe6fb2a - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x564e1fe6fb2a - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x564e1fe8af2a - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x564e1fe8aef4 - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x564e1fe8aead - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x564e1fdfa3f0 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x564e1fdfcd42 - core::option::expect_none_failed::h6154dc750ae47ade
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
  16:     0x564e1fe0cf25 - exa::output::table::Table::display::hbddccbc00d23f963
  17:     0x564e1fe11c7d - exa::output::table::Table::row_for_file::h5bdd9f570afeb644
  18:     0x564e1fe144d0 - <F as scoped_threadpool::FnBox>::call_box::h967429d8580269ad
  19:     0x564e1fe6a3ed - std::sys_common::backtrace::__rust_begin_short_backtrace::h45cf98b86d39c80c
  20:     0x564e1fe6adbe - core::ops::function::FnOnce::call_once{{vtable.shim}}::h7629eca93c328fb3
  21:     0x564e1fe91df5 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hbb39a3e615f69ef9
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  22:     0x564e1fe91df5 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h79630a683aed732c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  23:     0x564e1fe91df5 - std::sys::unix::thread::Thread::new::thread_start::h4afaeade0da13617
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
  24:     0x7fc83e9cf6db - start_thread
  25:     0x7fc83f0a671f - __clone
  26:                0x0 - <unknown>
[1]    7942 abort      RUST_BACKTRACE=full exa -lh --git --all
```

**Comment by ariasuni** [comment]
This has been fixed in #670.

In the meantime, I guess you could see which file’s modified date is pre-EPOCH and use `touch` on them to update their modified time.

I’ll see what I can do to make a new release happen this year. Thanks for reporting!
