### ISSUE TITLE
Crash when using --long & --git flags when symbolic link target doesn't exist

### ISSUE THREAD

**Issue by jchilders** [ogham/exa#815]
Steps to reproduce:

```
$ touch hello
$ ln -s hello hello_link
$ rm hello
$ exa --long --git
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/fs/feature/git.rs:271:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort      exa --long --git
```

exa version: v0.9.0
Full stack trace:

```
$ RUST_BACKTRACE=full exa --long --git
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/fs/feature/git.rs:271:22
stack backtrace:
   0:        0x1006421df - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3b6ed74a60c4de30
   1:        0x1005cf20e - core::fmt::write::h72dd6ddbc116ef3c
   2:        0x100641d26 - std::io::Write::write_fmt::h033803ce14d847cc
   3:        0x100658122 - std::panicking::default_hook::{{closure}}::h040276b51a1a4749
   4:        0x1006588d3 - std::panicking::rust_panic_with_hook::h15f3dba6c099e04e
   5:        0x100642659 - std::panicking::begin_panic_handler::{{closure}}::h33fb39231ad9a88d
   6:        0x1006425c8 - std::sys_common::backtrace::__rust_end_short_backtrace::hd5ec6f84e4df1d34
   7:        0x1006577c0 - _rust_begin_unwind
   8:        0x1006c754f - core::panicking::panic_fmt::h7889f3b8e7c118f7
   9:        0x1006c7105 - core::result::unwrap_failed::h095cbf11d4909cd8
  10:        0x1005f7dd6 - exa::fs::feature::git::reorient::h72cc0e6c6efbe44e
  11:        0x1005f7830 - exa::fs::feature::git::Git::status::h009a8b982f236485
  12:        0x1005dc4e6 - exa::output::table::Table::display::h2236baf7ab18a23d
  13:        0x1005e015b - exa::output::table::Table::row_for_file::hd2b91f35518a15d5
  14:        0x1005e2b01 - <F as scoped_threadpool::FnBox>::call_box::hdcb1b34ebcfec947
  15:        0x1006358c1 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcf0c0b31e61213ca
  16:        0x100634713 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1169b407b1d85e41
  17:        0x10065c619 - std::sys::unix::thread::Thread::new::thread_start::hed7aa7efa61a9b35
  18:     0x7fff20513950 - __pthread_start
zsh: abort      RUST_BACKTRACE=full exa --long --git
```

**Comment by ariasuni** [comment]
This issue is the same as #526, and that it has been fixed in #584, there just hasn’t been a new release made since then.
