### ISSUE TITLE
Panic on `--help` and `--version` when stdout is closed

### ISSUE THREAD

**Issue by lopopolo** [ogham/exa#984]
```console
$ RUST_BACKTRACE=1 exa --version | false
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:940:9
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: std::io::stdio::_print
   3: exa::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
$ RUST_BACKTRACE=1 exa --help | false
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:940:9
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: std::io::stdio::_print
   3: exa::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
$ exa --version
exa - list files on the command-line
v0.10.1 [+git]
https://the.exa.website/
```

**Comment by rodolfoap** [comment]
This could be similar:
```
$ /bin/exa 
bin  Downloads  git  tra  wrk

$  /bin/exa -l
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/fs/file.rs:476:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

$ RUST_BACKTRACE=1 /bin/exa -l
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/fs/file.rs:476:68
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted

$ RUST_BACKTRACE=full /bin/exa -l
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/fs/file.rs:476:68
stack backtrace:
   0:     0x5584e8e3f777 - <unknown>
   1:     0x5584e8dc94ef - <unknown>
   2:     0x5584e8e39641 - <unknown>
   3:     0x5584e8e5535c - <unknown>
   4:     0x5584e8e3fafa - <unknown>
   5:     0x5584e8e3fac4 - <unknown>
   6:     0x5584e8e54c1d - <unknown>
   7:     0x5584e8dcb760 - <unknown>
   8:     0x5584e8dc66d2 - <unknown>
   9:     0x5584e8deb6e2 - <unknown>
  10:     0x5584e8e079bc - <unknown>
  11:     0x5584e8e0c402 - <unknown>
  12:     0x5584e8e0f8b3 - <unknown>
  13:     0x5584e8e0aaf2 - <unknown>
  14:     0x7f497f27ed0a - __libc_start_main
  15:     0x5584e8db609a - <unknown>
  16:                0x0 - <unknown>
Aborted
$
```

**Comment by ariasuni** [comment]
Nice catch. Fixed in https://github.com/ogham/exa/commit/df4fb84ae19267b534beb94560da524fc72f436b.
