### ISSUE TITLE
Thread 'main' panicked at 'called `Result::unwrap()` on an `Err`

### ISSUE THREAD

**Issue by rodolfoap** [ogham/exa#987]
Just installed debian 11 (x86_64) and I use i3wm. I notice this (not permanent):
```
$ /bin/exa 
bin  Downloads  git  tra  wrk

$ /bin/exa -l
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/fs/file.rs:476:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

$ RUST_BACKTRACE=1 /bin/exa -l
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/fs/file.rs:476:68
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted

$ RUST_BACKTRACE=full /bin/exa -l
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/fs/file.rs:476:68
stack backtrace:
   0:     0x5584e8e3f777 - <unknown>
   1:     0x5584e8dc94ef - <unknown>
   2:     0x5584e8e39641 - <unknown>
   3:     0x5584e8e5535c - <unknown>
   4:     0x5584e8e3fafa - <unknown>
   5:     0x5584e8e3fac4 - <unknown>
   6:     0x5584e8e54c1d - <unknown>
   7:     0x5584e8dcb760 - <unknown>
   8:     0x5584e8dc66d2 - <unknown>
   9:     0x5584e8deb6e2 - <unknown>
  10:     0x5584e8e079bc - <unknown>
  11:     0x5584e8e0c402 - <unknown>
  12:     0x5584e8e0f8b3 - <unknown>
  13:     0x5584e8e0aaf2 - <unknown>
  14:     0x7f497f27ed0a - __libc_start_main
  15:     0x5584e8db609a - <unknown>
  16:                0x0 - <unknown>
Aborted

$
```
- The version of exa being used (`exa --version`)
```
$ /bin/exa --version
exa v0.9.0
```
- Your operating system and hardware platform
```
$ cat /etc/issue.net 
Debian GNU/Linux 11

$ uname -a
Linux lap 5.14.0-0.bpo.2-amd64 #1 SMP Debian 5.14.9-2~bpo11+1 (2021-10-10) x86_64 GNU/Linux

$ head -1 /proc/meminfo 
MemTotal:        5971156 kB

$ cat /proc/cpuinfo|grep 'model name' 
model name	: Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz
model name	: Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz
model name	: Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz
model name	: Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz
```

**Comment by rodolfoap** [comment]
Nevermind, installed manually the version here and seems working. Just leaving this here for reference.

**Comment by ariasuni** [comment]
Yeah it’s a known issue, fixed since ages. I think it’s an issue that only happens with `--git`, though.
